### ISSUE TITLE
Where do I find /root/plot_manager/kill_nc.sh ?

### ISSUE THREAD

**Issue by miketweaver** [rjsears/chia_plot_manager#17]
Where do I find the contents of the script `/root/plot_manager/kill_nc.sh` ?

**Comment by miketweaver** [comment]
As well as `/root/plot_manager/receive_plot.sh`

**Comment by rjsears** [comment]
`/root/plot_manager/receive_plot.sh` is created on the fly when you run `./drive_manager.py`, take a look at lines 500 - 507 of `drive_manager.py`.

I will add `kill_nc.sh` to the chianas directory! Thanks for pointing that out!

**Comment by rjsears** [comment]
Information updated.
