### ISSUE TITLE
Import Error with psutil._common

### ISSUE THREAD

**Issue by TnzGit** [rjsears/chia_plot_manager#29]
First of all, thank you for putting so much time and effort for making this. I was almost going to attempt doing this (probably a much simpler version since I'm pretty newbie with coding).

I believe I've done all the required setting up, I've changed the directories to suit mine etc. 

When I was trying to run drive_manager.py, below error came up:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/txny/chia_plot_manager/chianas/drive_manager.py", line 68, in <module>
    from psutil._common import bytes2human
ImportError: cannot import name 'bytes2human' from 'psutil._common' (/usr/lib/python3/dist-packages/psutil/_common.py)
```

Any ideas? I do have psutil installed.

**Comment by rjsears** [comment]
That generally happens when you have the wrong version of psutil installed. You can check by doing the following:

    Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
    [GCC 9.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import psutil
    >>> psutil.__version__
    '5.8.0' 
    >>>

**Comment by rjsears** [comment]
Did this take care of your problem?

**Comment by TnzGit** [comment]
Sorry for delayed response, been away from home last couple of days. Yes
that has solved the psutil issue! Thank you for your help again.

**Comment by rjsears** [comment]
Awesome! Thanks
