### ISSUE TITLE
per_coin = True in coin_monitor_config

### ISSUE THREAD

**Issue by erdincsk** [rjsears/chia_plot_manager#33]
Hello, i am not a software deloveper, i was just trying to use your script -> coin_monitor.py

i could not run your script without changing per_coin = True to per_coin_email = True in coin_monitor_config

after chaning that it is working.

maybe this is something to fix. i just wanted to let you know. thanks.

**Comment by rjsears** [comment]
Thank you, yes I had altered the ode and forgotten to update the coin_monitor_config file!

I appreciate you letting me know so I could change it.
