### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by olivierLA75** [rjsears/chia_plot_manager#34]
Hey there, you did a really good job with the Chia plot manager. I'm looking for some advice to set up my Chia plotting and farming, same kind of system that you have. would you give me a little hand to pick the devices? also I was wondering how many plots you were able to make a day with your system? 
thanks in advance!
best,
olivier

**Comment by rjsears** [comment]
Hi Oliver - 

Always happy to assist. I have listed the hardware that I use for both my main plotter as well as my NAS/Harvester/secondary plotter at the bottom of the main readme. Currently, I am able to produce around 110 to 120 K32 plots every 24 hours with these two systems. 

Please let me know if you have any other questions.

**Comment by olivierLA75** [comment]
Thank you for taking the time to reply to me. Yes, I have a few other simple questions and it would be really appreciated if you could look at those. Maybe you could send me an email to ***@***.*** and I will reply to you with my questions so it doesn’t appear on the GitHub wall?
Thanks in advance!
Olivier

**Comment by michal-ambroziak** [comment]
Hi rjsears,
So you have 3rd server with proxmox running VM with farmer node, how do you mount plots from NAS?

**Comment by rjsears** [comment]
Hi Oliver -

Github scrubbed your email address. I don't mind your questions here on
github as they may help someone else. If you would rather chat via email my
email is richardjsears at gmail dot com


                      Richard J. Sears
                      ATP ASMEL/Rotor, CFI, CFII, MEI
                      G-V / CE-525S / CE-500 / S-70

**Comment by rjsears** [comment]
> Hi rjsears,
> So you have 3rd server with proxmox running VM with farmer node, how do you mount plots from NAS?

Yes, I have a Ubuntu 20.04 desktop install that runs my farmer/wallet. You do not need to mount anything to get it to work, on your harvester you point to the IP address of your farmer, Chia does the rest.
