### ISSUE TITLE
k32 plots have different sizes

### ISSUE THREAD

**Issue by maxbelz** [rjsears/chia_plot_manager#41]
# Are we testing?
testing = False
if testing:
    plot_dir = '/home/chia/plot_manager/test_plots/'
    plot_size = 10000000
    status_file = '/home/chia/plot_manager/transfer_job_running_testing'
else:
    plot_dir = "/mnt/ssdraid/array0/"
    plot_size = 108644374730  # Based on K32 plot size
    status_file = '/home/chia/plot_manager/transfer_job_running'

remote_checkfile = '/root/plot_manager/remote_transfer_is_active'

Just saw that in installation instruction, after checking my files i saw that they have different sizes. looks like according to this code file size have to be exatly 108644374730 or it wont be validated as successful plot. but all plots are valid even they have different sizes...

**Comment by maxbelz** [comment]
ok, sorry looks like you fixed it in Fixed get_list_of_plots() #11 right?

**Comment by rjsears** [comment]
Not really, the plot_size is the `minimum` size of the plot, not the exact size of the plot. 

`plot_to_process = [plot for plot in pathlib.Path(plot_dir).glob("*.plot") if plot.stat().st_size > plot_size]`

**Comment by rjsears** [comment]
Please feel free to reopen if you need moren information.
