### ISSUE TITLE
Multiple plotter support

### ISSUE THREAD

**Issue by mtrogers** [rjsears/chia_plot_manager#45]
Does this support a single-nas, many (10+) plotter node configuration?

**Comment by rjsears** [comment]
One of the things on my roadmap is to set the plot_manager.py to be able to communicate with multiple NAS/Harvesters, determine which one has the least amount of plots, and then made a decision which NAS/Harvester to send the plot to based on that information. 

My latest release now includes the ability to gather all the required information for each NAS/Harvester, however I have not integrated that into plot_manager.py as of yet.

It is coming soon!

**Comment by maxbelz** [comment]
we are waiting for multiple plotters to 1 harvester/farmer so much. thank you!

**Comment by maxbelz** [comment]
@rjsears looks like you would better to take a look at socat vs netcat , because netcat doesnt support multiple clients.. just reading about that and sharing with you..
