### ISSUE TITLE
Script acknowledge

### ISSUE THREAD

**Issue by iwbrhwfy** [rjsears/chia_plot_manager#46]
Would you please expose your chia command script or one single commnad line considering your plotter-harvester async structure? And plotman script based on one local plotter? Thank you~!

**Comment by rjsears** [comment]
Hi - I am happy to help but have no idea what you are asking for here. I did not write plotman so I can't help you there.

**Comment by iwbrhwfy** [comment]
> Hi - I am happy to help but have no idea what you are asking for here. I did not write plotman so I can't help you there.

Do you start pooling with chia command line or plotman? How do you set your command line parameter or plotman.yaml? Could you please let me kown if possible? Thank you~!

**Comment by rjsears** [comment]
I'm sorry, but I do not do any pooling at all...you might want to reach out to some of the folks on keybase for that information.

**Comment by iwbrhwfy** [comment]
> I'm sorry, but I do not do any pooling at all...you might want to reach out to some of the folks on keybase for that information.

I'm quite sorry for typing mistake. I mean plotting, but not pooling...sorry for that~

**Comment by maxbelz** [comment]
> > I'm sorry, but I do not do any pooling at all...you might want to reach out to some of the folks on keybase for that information.
> 
> I'm quite sorry for typing mistake. I mean plotting, but not pooling...sorry for that~

@rjsears 's project is not about plotting at all. it's only about moving already plotted plots to your farm-machine. dont ask here for anything about plotting. thank you.

**Comment by rjsears** [comment]
@maxbelz is quite right, this is from the install doc:

**_In its simplest form, chia_plot_manager bridges the gap between creating a plot, and managing that plot after it has been created._**
