### ISSUE TITLE
First plot of the job end after 20 minutes

### ISSUE THREAD

**Issue by bouzaguido** [rjsears/chia_plot_manager#49]
Hi! 
When i put 3 plot in paralell in the same job, the first end after 20 minutes, that generate one new plot (only 3 in phase 1 whit my 1tb nvme) and all continuos fine. 
Just the first plot have this issue, the others plots goes to the end. Thx!

**Comment by maxbelz** [comment]
@rjsears 's project is not about plotting at all. it's only about moving already plotted plots to your farm-machine. dont ask here for anything about plotting. thank you.
