### ISSUE TITLE
receive_plot.sh empty with non-standard file structure (no front/rear)

### ISSUE THREAD

**Issue by rglastra** [rjsears/chia_plot_manager#53]
Hi,

As alluded to in my earlier issue (https://github.com/rjsears/chia_plot_manager/issues/52), my drive structure doesn't include a front/rear because all my enclosures are front-facing. As such, I removed this from my drive_structures file.
I also go by rows rather than column (but I expected there to be minor issues with that), so that required some minor work.

However it appears `drive_manager.py` is hardcoded to look for the front/rear mountpoint pattern, failing to create a working `receive_plot.sh` upon first run of `python3 drive_manager.py`. Which in turn leads to unsuccessful plot transfers (I was getting "Remote NC kill!").
It would be fantastic if it could deduce the pattern from the drive_structures file instead.

To manually fix this for now I had to:
- Open `drive_manager.py`, for `get_path_info_by_mountpoint` change the second entry from:

```
    elif info == 'column':
        return (mountpoint.split("/")[5])
```

To:
```
    elif info == 'row':
        return (mountpoint.split("/")[4])
```

- Remove receive_plot.sh, transfer_is_active (on the harvester) and transfer_job_running (on the plotter side)
- Re-run `python3 drive_manager.py` on the harvester
- Re-run `python3 plot_manager.py` (or wait for the cronjob to kick in).

**Comment by rjsears** [comment]
That is a great idea! I am not sure using the drive_structure file is the best way as I was using that as example structures (for example we could add your structure as one of the possible structures) but there should be a way to alter the ```elif info == 'column`:``` part to work with the scripts. 

I am going to work on that when I have some time to see if I can make it easier. In the meantime I added notes to the script itself which may better help others.
