### ISSUE TITLE
replace_plot() Script on Failed

### ISSUE THREAD

**Issue by jobsidi** [rjsears/chia_plot_manager#64]
I'm getting this error: "replace_plot() Script on Failed"
What does it mean?
Help pls.
ps i have mount points like
"/mnt/enclosure0/column0/drive0"
so it must work with condition
p.device.startswith('/dev/sd') and p.mountpoint.startswith('/mnt/enclosure') and p.mountpoint.endswith(drive)

**Comment by rjsears** [comment]
I think that it means that your harvester is not set up correctly. On your harvester when you run ```./drive_manager.py -rp``` manually, what do you get?

**Comment by jobsidi** [comment]
-rp "It might DELETE an old plot" hmm but i dont want to delete all plots. All my plots are nft and correct. Is there any other option without deletion?

**Comment by rjsears** [comment]
If you do not need to replace old plots you should set your config to false for replacing plots, it will never run the ```replace_plot()``` script. That i ONLY run IF you tell the system you have old plots to replace. Since you have nft, this should be set to false.
