### ISSUE TITLE
Can we make it work on windows too?

### ISSUE THREAD

**Issue by pajtimrexhepi** [rjsears/chia_plot_manager#68]
I started all my work on windows. I cannot go to linux now, i have to many plots and many more comming. It would be great to have a windows version too. Thank you :)

**Comment by rjsears** [comment]
Hi @pajtimrexhepi 

Unfortunately I am not a windows programmer nor use windows for anything at all so I don't have any plans, or even a basic idea, of how to make this work in a windows environment.
